name: async_cubits
description: A set of cubits that can be used to handle async operations in a simple, consistent way.
version: 0.2.0
repository: https://github.com/jarekb123/async_cubits

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  meta: ^1.16.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
