name: async_cubits
description: A set of cubits that can be used to handle async operations in a simple, consistent way.
version: 0.3.0
repository: https://github.com/jarekb123/async_cubits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  meta: ^1.8.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^10.0.0
